version: '2'

services:
    app:
        build: .
        volumes:
            - ./app:/app
            - /app/node_modules
        ports:
            - 3030:3000
            - 35729:35729
        command: npm start
