version: '2'

services:
    app:
        build: .
        volumes:
            - ./app:/app/src
            - /app/src/node_modules
        ports:
            - 3000:3000
        command: pm2 start -x ./bin/www --no-daemon
